---
# Source: hostnetwork-webhook-admission-controller/templates/serviceaccounts.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "hostnetwork-webhook-admission-controller"
  namespace: kube-system
  labels:
    app: hostnetwork-webhook-hostnetwork-webhook-admission-controller

---
# Source: hostnetwork-webhook-admission-controller/templates/rbac.yaml

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hostnetwork-webhook-hostnetwork-webhook-admission-controller-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["extension-apiserver-authentication"]
  verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hostnetwork-webhook-hostnetwork-webhook-admission-controller-role-binding
subjects:
- kind: ServiceAccount
  name: hostnetwork-webhook-admission-controller
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: hostnetwork-webhook-hostnetwork-webhook-admission-controller-role
  apiGroup: rbac.authorization.k8s.io
---
# Source: hostnetwork-webhook-admission-controller/templates/hostnetwork-webhook-admission-controller-service.yaml
kind: Service
apiVersion: v1
metadata:
  name: hostnetwork-webhook-hostnetwork-webhook-admission-controller
  namespace: kube-system
  labels:
    app: hostnetwork-webhook-hostnetwork-webhook-admission-controller
spec:
  type: NodePort
  selector:
    app: hostnetwork-webhook-hostnetwork-webhook-admission-controller
  ports:
  - port: 443
    targetPort: 8443

---
# Source: hostnetwork-webhook-admission-controller/templates/hostnetwork-webhook-admission-controller-deployment.yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hostnetwork-webhook-hostnetwork-webhook-admission-controller
  namespace: kube-system
  labels:
    app: hostnetwork-webhook-hostnetwork-webhook-admission-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hostnetwork-webhook-hostnetwork-webhook-admission-controller
  template:
    metadata:
      labels:
        app: hostnetwork-webhook-hostnetwork-webhook-admission-controller
    spec:
      serviceAccountName: "hostnetwork-webhook-admission-controller"
      hostNetwork: true
      containers:
      - name: webhook
        image: pupapaik/hostnetwork-webhook-admission-controller:latest
        imagePullPolicy: Always
        command: ["/hostnetwork-webhook-admission-controller"]
        args:
        - --logtostderr
        - -v=4
        - 2>&1
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 8443
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: certs
          mountPath: /var/run/hostnetwork-webhook-admission-controller
          readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: hostnetwork-webhook-hostnetwork-webhook-admission-controller-cert

---
# Source: hostnetwork-webhook-admission-controller/templates/admissionregistration.yaml

apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: hostnetwork-webhook-hostnetwork-webhook-admission-controller
  labels:
    app: hostnetwork-webhook-hostnetwork-webhook-admission-controller
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBVENDQWVtZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFpTVNBd0hnWURWUVFERXhkaFpHMXAKYzNOcGIyNHRZMjl1ZEhKdmJHeGxjaTFqWVRBZUZ3MHhPREE1TWpVd09EVXdNREphRncweU9EQTVNakl3T0RVdwpNREphTUNJeElEQWVCZ05WQkFNVEYyRmtiV2x6YzJsdmJpMWpiMjUwY205c2JHVnlMV05oTUlJQklqQU5CZ2txCmhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBM0VxQlNNbFpvcW11akRoTEczTnR0M2JMSThKR1pVMUIKeXhuVnA5WTZNWEQvR0FydnpnSHFJdEZPZVE4UDZnbTRCOVB3S0p6MDhzSG5Sck95K2ppQW5HbkJ3YVM4bEptWgoxWFA0ckNpUjRpcGMzOHZEU0Q0MjhDa01IejBjRHgvRDBpdy9tRmhpZkZHZFZ0UjE0dTV1Uzc1QjFUa1dCWUJXCmhGWkNFTERaMGRhdDBnQkc3VmdDdTZDVjg3VThVM0taMk9aUXlSSElnVjQ0UlN1Kzd1OGdnclE1SXpMdnFvc2QKaWVMRVVrK3hxN2FpZlp3c3NoQmk1ZjVlMkpDWE85SERZTmtOYnV4d1JVdFltUUFpSmIwZ0NsYk5zSi9HczR5agpFVXFPNGcyMW5oZmpjbGxWcGpSdFpFZEZJTXhWMDVXNW5NKzhnaUI4QjNhNXloQkdvQ2llTlFJREFRQUJvMEl3ClFEQU9CZ05WSFE4QkFmOEVCQU1DQXFRd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUMKTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUpLOHFqNi80cGR5NEpEaAozdVM1djRHblZrSEdqVzRMVzErUUFkWlc3R3M2NXE0Q1NKRG8ydmFhdWZiRVJVb09sR25PNVNkMkRRaXAyOCtJCk9rM2cxRzQvTEdMbmxQa21SMFA1dmVjMHNJU3RHREU4UFlNT1hGWEJKRndydnZ2cXRITWpvRzhqaWs2MGNIMkwKd1pPZUlIY2drU0laQWUzUXdERzIvWGYvVHhlWFRFVVh2MXZLVUl1dndCT1ltRWt6Y003SkhiMmNpUUtnYUI0VQo5OUxYeXc5S0t1WFV6OXhldGZSY3BEczVmcGJHV0NBMW4rcDdPM1dNOTBET3RjckhmN01NemVuWkdyaUcrZzA1CkxIMklUUFNUV0gxSjhITTFRSVBYbFV4eUhjS3pXdkg4UUxCdWFLYmxSQTEzZzBldGVVd0JoMk40dWdaMzNPYXkKam9qVTZUbz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: hostnetwork-webhook-hostnetwork-webhook-admission-controller
      namespace: kube-system
      path: /mutating-services
  failurePolicy: Ignore
  name: hostnetwork-webhook-hostnetwork-webhook-admission-controller.k8s.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
---
apiVersion: v1
kind: Secret
metadata:
  name: hostnetwork-webhook-hostnetwork-webhook-admission-controller-cert
  labels:
    app: hostnetwork-webhook-hostnetwork-webhook-admission-controller
type: Opaque
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR5ekNDQXJPZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFpTVNBd0hnWURWUVFERXhkaFpHMXAKYzNOcGIyNHRZMjl1ZEhKdmJHeGxjaTFqWVRBZUZ3MHhPREE1TWpVd09EVXdNREphRncweU9EQTVNakl3T0RVdwpNREphTUVjeFJUQkRCZ05WQkFNVFBHaHZjM1J1WlhSM2IzSnJMWGRsWW1odmIyc3RhRzl6ZEc1bGRIZHZjbXN0CmQyVmlhRzl2YXkxaFpHMXBjM05wYjI0dFkyOXVkSEp2Ykd4bGNqQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQUQKZ2dFUEFEQ0NBUW9DZ2dFQkFObS84ZVBtYXRGMXZOTllkQ0w3UDdZd0U1eUJ1aU1KdnpoSDRzdFhNZWFCckc4SAoxelFUbVB6eFhMTFZaQkxKTHpZaHh5dE16QTd3Z3h2eWQrN1RKaVRuMjZEV2UxM2tkY2lXMWlHUUYxVGxDZmtpCkkxM1d1L1FWa1lQdFVDYjRmVW9jb013Qi82N0xEbHFpWmVJZ2lHb2tLZGhkY0FDS0VYRXFoYWhPUDF1Y0ZWUEYKVVR4V2lrcXUyUTZTMjduVFZvSE04MGtvMUl4a2tKcm5oeDdYbHJXdXJud0hQcEoxNWU1bnhLelBQLzNzNGxMVQo0NUVEM0E2UlRlK3JTTG5KakttalpHNHlFSy9BNTBUSUJpaTUzQzdLTnhjcGM2QU1OQjRzUTVwMnNuU1hWdTNtCkdIcnp3TVdsUkczTzlETG1penlQamtaNEVDYm05L1hHc0tpcUxpMENBd0VBQWFPQjVqQ0I0ekFPQmdOVkhROEIKQWY4RUJBTUNCYUF3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01Bd0dBMVVkRXdFQgovd1FDTUFBd2dhTUdBMVVkRVFTQm16Q0JtSUpJYUc5emRHNWxkSGR2Y21zdGQyVmlhRzl2YXkxb2IzTjBibVYwCmQyOXlheTEzWldKb2IyOXJMV0ZrYldsemMybHZiaTFqYjI1MGNtOXNiR1Z5TG10MVltVXRjM2x6ZEdWdGdreG8KYjNOMGJtVjBkMjl5YXkxM1pXSm9iMjlyTFdodmMzUnVaWFIzYjNKckxYZGxZbWh2YjJzdFlXUnRhWE56YVc5dQpMV052Ym5SeWIyeHNaWEl1YTNWaVpTMXplWE4wWlcwdWMzWmpNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFQCnhWcWtYUFpHM2srRmtNdW1MeVA2eGkxZUJrN3FXOFlTdWlMMWgrRTFJb2swRkZpeHBEYWUwN0NJQVdBeDZrMlUKVjBreFlqMFR1bTBhOVJwVWwxenpOdzFCTmV2dFBibkRuRE51UTlLd0hHQ2pwekw1bi9OZXVtdGFSTitVUkJqegpXL1VFcmpCaUtFbHhHYXllZjNvVFZlQUVXSy8zQlh0TE0xNkFWV2Z0OTNjNmFGWWh3OTFoZVBLL2NhWitRTnV5CkVLZndrcGFQbDdhKzkydSs4aHZNQ1FYcE1aNlBydGptVjlCVG9ZRjFLcjJ6alRvM0R3Mk9QMjduQjBZOThPdHMKeXo0V01NNjRBdzlhM2NOUHZLd1N6R0Jaalp1YkNidUI2blc3WnhNNWEyd1BZbVE0azBDRFVsNDBQeWFYckY0SQpueWpMQ1FhQ1dKM0pka2w4MU1kdgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBMmIveDQrWnEwWFc4MDFoMEl2cy90akFUbklHNkl3bS9PRWZpeTFjeDVvR3Nid2ZYCk5CT1kvUEZjc3RWa0Vza3ZOaUhISzB6TUR2Q0RHL0ozN3RNbUpPZmJvTlo3WGVSMXlKYldJWkFYVk9VSitTSWoKWGRhNzlCV1JnKzFRSnZoOVNoeWd6QUgvcnNzT1dxSmw0aUNJYWlRcDJGMXdBSW9SY1NxRnFFNC9XNXdWVThWUgpQRmFLU3E3WkRwTGJ1ZE5XZ2N6elNTalVqR1NRbXVlSEh0ZVd0YTZ1ZkFjK2tuWGw3bWZFck04Ly9lemlVdFRqCmtRUGNEcEZONzZ0SXVjbU1xYU5rYmpJUXI4RG5STWdHS0xuY0xzbzNGeWx6b0F3MEhpeERtbmF5ZEpkVzdlWVkKZXZQQXhhVkViYzcwTXVhTFBJK09SbmdRSnViMzljYXdxS291TFFJREFRQUJBb0lCQVFDcmNLdXpZb1F4bkVCcQpLaGR1UDJFZlFXVC9jVWdyTkE1ZzhvQkcxc1VNRm9hNytIRmdxQmxvOVdPbHpjcjMyM3lYWXlyY0ZhQUlGeWN6CkJzbVV1Sndzckh4SWV2WXdxNkpzcHcyNjZTYmxpVnM3MHJ3RHN3RFNvWFNyYVZvVkJNb29ZcmZiUjZ1V1pIdE4Kc3RVQ245aW5zUWRkT2R2b0lNeXd5K2psNVkyT3dyVnBoT3hSc2ZNc1M4TDNYYlVKS0d0bFU2QU1rRUdoMjZYUgpxMjhBWk0vd2wzblN1MGFkeEw1VENvdWFsakxvWnpwanRBbFdBcWVaWU9teFdKUDZXdzcrSHZxUHN0eUdadUhqCmhtMGN6RFFqOTZNZjJ4NXVrR3MyMGxZc3ZIc2dNd29WYXFKanFUQldnamVVaDJ3Q2h0Mkw0a1FzRTEvLzIzTFAKSDZaTHpTQkJBb0dCQVAzWE05Ymo3YUpIQ0g3bjgvbVQvOUh2SkhYZFZXVU5wR3dTRTdpSXloRDFycWpRTFY0TApaS3h3RDBKa2llK21VWmJ1NldIYTJnYkFTcmZvUjlXL2dOb20xd2pkdURVd28zMWU4Z3NKdnJHUlN3WDNYa3ZlCkUwclhSMVY1REhnT1hrd0VTYUxTaW41VE5aRWN3cWlZY3ZCTUhieU9PSWdNNWtqVHhXR3JYQVNSQW9HQkFOdWEKSldhbFViQWFqbjhxc01ncWVRWjZFSkVsZ3lqK2REZE5PSHFsYWY3Q2pGT2grUHBiS2FKSExTT0FFbWN5TTlKbgpTK2UvQmo5Yjc4d0txVjlpdkJ4MFZNYXlNM21MSjI4aWk5SVlPT0xEcVJtUGM4UFFLdHp5WXBTOTVHcW1YMERoCk0vNmlTVGdoQWhSTURwSGxVdC83Z1IxZm1ldi9OdFZ6akIvcUFPM2RBb0dBZVFFQ1JEanBDY2VFeEVJOEtrZ2oKMWVhQzRmQzlpV3VFYXNQL1JLTm9kOGMyR0dFTWoxMHRBNHB6cTdtVGkzc2tQNmZwOXV6RnJCdzBRaERuVlh4eApwd3lHeTBJdVVxUzUrc1NzNnhnZElEWmJwaDl5Z3dYOCtscy9OUDU4TkNyZFJxMXdrTDUrcUpOdjRKbnVMVUptCjRDZllzUTYyNGh3TUZzRmt3UmRYeVJFQ2dZRUFwMUFPWnVKV0ZxSmxKeVpUZ200NXYyR0k5YzFxM1BUaGZyRHEKOHliTVZ6bkt5SDJEd050c0lTT3hsSGFqanRTRS95Mk1lNGpqTGFyU1ROZGlyRFlCdEh3OWl4V0NlbnczRTBseQoxaU4yVSs5WEN3NXMyU2ZsUUdtOENpK1R0RjRGL055WVRNMUFrKzh5TWx5d1RTQTN3RWRTM0JwV242UFhGMUh0CjFQTG91bEVDZ1lCdkRwQUwwc040UDIvYkw3ZjZOUjhtdzdDMVhpR3dVVFJBcGh3YmRCUSt6VjdHTTVoamVXcloKYjV1TGhNRjJFeGJONUltR0UxaWtUQVNaYm9pbVhiNTc1Y2tjWXZrRWloNGlNbkVzb21ZcENrTGFOaTNIVkpWbgpuc28xVUg5RWV4TmtycWRIT1ZKbnc2VytuWC9aTnYwRFZDcTBvMTNKeUpjNkU4TUVVUmQ5OUE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=

